[workspace]

members = [
  "dale",
  "dale-derive",
  "dale-http",
  "dale-fs",
  "dale-runtime",
  "dale-extensions",
  "dale-http-cookies",
  "dale-http-session",
  "dale-http-negotiate",
  "dale-http-rest",
]
