[package]
edition = "2021"
name = "dale-derive"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1"
proc-macro2 = "1"
quote = "1"
syn = {version = "1", features = []}
